### ISSUE TITLE
Cygwin cookiecutter fails

### ISSUE THREAD

**Issue by jwgulley** [OasisLMF/cookiecutter-OasisModel#7]
Reading the documentation, I set up my SSH key pair with git hub and the SSH key server using the github instructions and tested it using:

  ssh -T git@github.com

Here is the reply:

Hi jwgulley! You've successfully authenticated, but GitHub does not provide shell access.

I take that to mean all is well.

I then ran the following in a clean directory:

cookiecutter git+ssh://git@github.com/OasisLMF/cookiecutter-OasisModel

I take the defaults for all options, except for jwgulley as the maintainer, jon.gulley@ambiental.co.uk as the email address and Ambiental as the organisation.

The end of the output indicates that this does not work - as follows:

"Adding Oasis repositories as Git submodules in C:\cygwin64\home\oasis\test3\OM\src.

Traceback (most recent call last):
  File "c:\cygwin64\tmp\tmprqufe8.py", line 63, in <module>
    add_git_submodules()
  File "c:\cygwin64\tmp\tmprqufe8.py", line 34, in add_git_submodules
    'git', 'checkout', 'master'
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'submodule', 'add', '-f', 'git+ssh://git@github.com/OasisLMF/oasis_utils', 'src\\oasis_utils', 'git', 'checkout', 'master']' returned non-zero exit status 128
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)"

In order to progress this, I took a clone of cookiecutter-OasisModel, created a directory for the test and ran the test as follows:

cookiecutter ../cookiecutter-OasisModel

This produced results similaer/identical to the above, but if I comment out the following lines from hooks/post_gen_project.py as follows...

    '''
    print('\nAdding Oasis repositories as Git submodules in {}.\n'.format(os.path.join(cwd, 'src')))
    time.sleep(2)
    add_git_submodules()
    
    print('\nCommiting Git submodules.\n')
    time.sleep(2)
    commit_git_submodules()

    print('\nAdding Oasis base lookup class to keys server subpackage.\n')
    time.sleep(2)
    add_static_base_lookup_module_to_keys_server_subpackage()
    '''

...I am able to get it to finish, albeit without the sub-modules.

**Comment by sr-murthy** [comment]
@jwgulley Firstly, sorry for forgetting to give you access to the OasisLMF/Ambiental repository. I've done this now. Your team should have full write access.

Thanks very much for raising this issue. It's an interesting one - the key line in the error message is this one

    subprocess.CalledProcessError: Command '['git', 'submodule', 'add', '-f', 'git+ssh://git@github.com/OasisLMF/oasis_utils', 'src\\oasis_utils', 'git', 'checkout', 'master']' returned non-zero exit status 128
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)"

The post-project creation/clone script used the `subprocess` library to make system calls to Git to add the needed submodules, which are `oasis_utils` and `oasis_keys_server`. These are meant to be added to/at the relative paths `src/oasis_utils` and `src/oasis_keys_server` inside the cloned repository. You can see that Python constructs the relative path with the wrong path separator

    'src\\oasis_utils'

The part of the command to this is

    check_call(['git', 'submodule', 'add', '-f', url, os.path.join('src', name) ...])

So the value of `os.path.join('src', name)` on Cygwin Python, where `name` will first be `oasis_utils`, is ending up as `src\\oasis_utils` instead of `src/oasis_utils` as it would be on Linux/OS X.

I will need to modify the script to detect the platform and construct any paths in a Windows-friendly way. 

Thanks.

**Comment by sr-murthy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cygwin/Windows path construction bug in cookiecutter post-project creation script](https://trello.com/c/Yj3MAOHN/234-cygwin-windows-path-construction-bug-in-cookiecutter-post-project-creation-script)
